---
title: "Saving supplementary files"
date: 'Date: `r format(Sys.Date(), "%B %d, %Y")`'
output:
    html_document:
        toc: true
        toc_float: true
        theme: 'united'
        highlight: 'kate'
        code_folding: hide
params: 
    SE_CTL04: '~/DataDir/bulkRNASeq/3.DataExploration/CTL04/Output/FemaleLineSE_Bio.rds'
    SE_CTL08: '~/DataDir/bulkRNASeq/3.DataExploration/CTL08/Output/AfterSamplesSelection/MaleLineSE_Bio.rds'

    DEA_CTL04: '~/DataDir/bulkRNASeq/5.DifferentialExpression/CTL04/DEARes.rds'
    DEA_CTL08: '~/DataDir/bulkRNASeq/5.DifferentialExpression/CTL08/DEARes.rds'

    OutputFolder: './3_DifferentialExpression/DEA_excel_files/'
---

# 1. Environment Set Up

Values of RMarkdown parameters
```{r EnvironmentSetupI, collapse=TRUE}
for (i in 1:length(params))
  print(paste('Parameter:', names(params)[i], ' - Value:', params[[i]], '- Class:', class(params[[i]])))
```

```{r EnvironmentSetupII, collapse=TRUE}
library(RNASeqBulkExploratory)  #Our Package
library(ggplot2)
library(gridExtra)
library(dplyr)
library(SummarizedExperiment)
```

# 2. Reference compounds

<!-- Saving CTL04 count matrix -->

<!-- ## 2.1 Count and sample matrices saving -->

<!-- ```{r} -->
<!-- SE_CTL04 <- readRDS(params$SE_CTL04) -->
<!-- SE_CTL04 <- SE_CTL04[!duplicated(rowData(SE_CTL04)$GeneName), ] -->
<!-- rownames(SE_CTL04) <- rowData(SE_CTL04)$GeneName -->
<!-- #SE_Bio <- RNASeqBulkExploratory::normTmmSE(SE_Bio) -->

<!-- write.table(assays(SE_CTL04)$counts, file = paste0(params$OutputFolder, "Counts_CTL04.txt"), quote = FALSE, sep = "\t") -->
<!-- #write.table(assays(SE_Bio)$logcpm[geneNames, ], file = "~/DataDir/Collaboration/Chris/Output/Genes_LogCpm.txt", quote = FALSE, sep = "\t") -->
<!-- ``` -->

<!-- ```{r} -->
<!-- colData(SE_CTL04) %>% colnames() -->
<!-- ``` -->

<!-- Saving CTL04 sample sheet -->

<!-- ```{r} -->
<!-- openxlsx::write.xlsx(colData(SE_CTL04) %>% as.data.frame() %>% dplyr::select(c("Condition", "Pathway", "Line", "Sex")), paste0(params$OutputFolder, "SampleSheet_CTL04.xlsx"), rowNames = TRUE, headerStyle = openxlsx::createStyle(textDecoration = "Bold")) -->
<!-- ``` -->

<!-- Saving CTL08 count matrix -->

<!-- ```{r} -->
<!-- SE_CTL08 <- readRDS(params$SE_CTL08) -->
<!-- SE_CTL08 <- SE_CTL08[!duplicated(rowData(SE_CTL08)$GeneName), ] -->
<!-- rownames(SE_CTL08) <- rowData(SE_CTL08)$GeneName -->

<!-- write.table(assays(SE_CTL08)$counts, file = paste0(params$OutputFolder, "Counts_CTL08.txt"), quote = FALSE, sep = "\t") -->
<!-- ``` -->

<!-- ```{r} -->
<!-- colData(SE_CTL08) %>% colnames() -->
<!-- ``` -->

<!-- Saving CTL08 sample sheet -->

<!-- ```{r} -->
<!-- openxlsx::write.xlsx(colData(SE_CTL08) %>% as.data.frame() %>% dplyr::select(c("Condition", "Pathway", "Line", "Sex", "SeqRun")), paste0(params$OutputFolder, "SampleSheet_CTL08.xlsx"), rowNames = TRUE, headerStyle = openxlsx::createStyle(textDecoration = "Bold")) -->
<!-- ``` -->

## 2.2 Saving all genes with p-value and DEGs

```{r, collapse=TRUE}
DEA_CTL08 <- readRDS(params$DEA_CTL08)
DEA_CTL04 <- readRDS(params$DEA_CTL04)
```

### Agonist Vs Inhibitor CTL04 

#### All

```{r}
list_DEA_CTL04 <- vector("list", length(names(DEA_CTL04))) %>% setNames(names(DEA_CTL04))

for (Cond in names(list_DEA_CTL04)) {
  list_DEA_CTL04[[Cond]] <- DEA_CTL04[[Cond]]$AgvsInh$Res %>% as.data.frame()
}

list_DEA_CTL04 <- list_DEA_CTL04 %>% setNames(paste0("DEA_", names(list_DEA_CTL04), "_AgvsInh"))

openxlsx::write.xlsx(list_DEA_CTL04, paste0(params$OutputFolder, "DEA_CTL04_AgvsInh.xlsx"), rowNames = TRUE, headerStyle = openxlsx::createStyle(textDecoration = "Bold"))
```

#### DEGs

```{r}
list_DEGs_CTL04 <- vector("list", length(names(DEA_CTL04))) %>% setNames(names(DEA_CTL04))

for (Cond in names(list_DEGs_CTL04)) {
  list_DEGs_CTL04[[Cond]] <- DEA_CTL04[[Cond]]$AgvsInh$DEGs %>% arrange(padj)
}

list_DEGs_CTL04 <- list_DEGs_CTL04 %>% setNames(paste0("DEGs_", names(list_DEGs_CTL04), "_AgvsInh"))

openxlsx::write.xlsx(list_DEGs_CTL04, paste0(params$OutputFolder, "DEGs_CTL04_AgvsInh.xlsx"), rowNames = TRUE, headerStyle = openxlsx::createStyle(textDecoration = "Bold"))

```

### Agonist Vs DMSO CTL04 

#### All

```{r}
list_DEA_CTL04 <- vector("list", length(names(DEA_CTL04))) %>% setNames(names(DEA_CTL04))

for (Cond in names(list_DEA_CTL04)) {
  list_DEA_CTL04[[Cond]] <- DEA_CTL04[[Cond]]$Agonist$Res %>% as.data.frame()
}

list_DEA_CTL04 <- list_DEA_CTL04 %>% setNames(paste0("DEA_", names(list_DEA_CTL04), "_AgvsDMSO"))

openxlsx::write.xlsx(list_DEA_CTL04, paste0(params$OutputFolder, "DEA_CTL04_AgvsDMSO.xlsx"), rowNames = TRUE, headerStyle = openxlsx::createStyle(textDecoration = "Bold"))
```

#### DEGs

```{r}
list_DEGs_CTL04 <- vector("list", length(names(DEA_CTL04))) %>% setNames(names(DEA_CTL04))

for (Cond in names(list_DEGs_CTL04)) {
  list_DEGs_CTL04[[Cond]] <- DEA_CTL04[[Cond]]$Agonist$DEGs %>% arrange(padj)
}

list_DEGs_CTL04 <- list_DEGs_CTL04 %>% setNames(paste0("DEGs_", names(list_DEGs_CTL04), "_AgvsDMSO"))

openxlsx::write.xlsx(list_DEGs_CTL04, paste0(params$OutputFolder, "DEGs_CTL04_AgvsDMSO.xlsx"), rowNames = TRUE, headerStyle = openxlsx::createStyle(textDecoration = "Bold"))

```

### Inhibitor Vs DMSO CTL04 

#### All

```{r}
list_DEA_CTL04 <- vector("list", length(names(DEA_CTL04))) %>% setNames(names(DEA_CTL04))

for (Cond in names(list_DEA_CTL04)) {
  list_DEA_CTL04[[Cond]] <- DEA_CTL04[[Cond]]$Inhibitor$Res %>% as.data.frame()
}

list_DEA_CTL04 <- list_DEA_CTL04 %>% setNames(paste0("DEA_", names(list_DEA_CTL04), "_InhvsDMSO"))

openxlsx::write.xlsx(list_DEA_CTL04, paste0(params$OutputFolder, "DEA_CTL04_InhvsDMSO.xlsx"), rowNames = TRUE, headerStyle = openxlsx::createStyle(textDecoration = "Bold"))
```

#### DEGs

```{r}
list_DEGs_CTL04 <- vector("list", length(names(DEA_CTL04))) %>% setNames(names(DEA_CTL04))

for (Cond in names(list_DEGs_CTL04)) {
  list_DEGs_CTL04[[Cond]] <- DEA_CTL04[[Cond]]$Inhibitor$DEGs %>% arrange(padj)
}

list_DEGs_CTL04 <- list_DEGs_CTL04 %>% setNames(paste0("DEGs_", names(list_DEGs_CTL04), "_InhvsDMSO"))

openxlsx::write.xlsx(list_DEGs_CTL04, paste0(params$OutputFolder, "DEGs_CTL04_InhvsDMSO.xlsx"), rowNames = TRUE, headerStyle = openxlsx::createStyle(textDecoration = "Bold"))

```

### Agonist Vs Inhibitor CTL08

#### All

```{r}
list_DEA_CTL08 <- vector("list", length(names(DEA_CTL04))) %>% setNames(names(DEA_CTL04)) #keep CTL04 to have the same order in the final file

for (Cond in names(list_DEA_CTL08)[names(list_DEA_CTL08) != "Estr"]) { #skip Estr condition because Estr inhibitor not available for CTL08
  list_DEA_CTL08[[Cond]] <- DEA_CTL08[[Cond]]$AgvsInh$Res %>% as.data.frame()
}

list_DEA_CTL08 <- list_DEA_CTL08 %>% setNames(paste0("DEA_", names(list_DEA_CTL08), "_AgvsInh"))

openxlsx::write.xlsx(list_DEA_CTL08, paste0(params$OutputFolder, "DEA_CTL08_AgvsInh.xlsx"), rowNames = TRUE, headerStyle = openxlsx::createStyle(textDecoration = "Bold"))
```

#### DEGs

```{r}
list_DEGs_CTL08 <- vector("list", length(names(DEA_CTL04))) %>% setNames(names(DEA_CTL04)) #keep CTL04 to have the same order in the final file

for (Cond in names(list_DEGs_CTL08)[names(list_DEGs_CTL08) != "Estr"]) { #skip Estr condition because Estr inhibitor not available for CTL08
  list_DEGs_CTL08[[Cond]] <- DEA_CTL08[[Cond]]$AgvsInh$DEGs %>% arrange(padj)
}

list_DEGs_CTL08 <- list_DEGs_CTL08 %>% setNames(paste0("DEGs_", names(list_DEGs_CTL08), "_AgvsInh"))

openxlsx::write.xlsx(list_DEGs_CTL08, paste0(params$OutputFolder, "DEGs_CTL08_AgvsInh.xlsx"), rowNames = TRUE, headerStyle = openxlsx::createStyle(textDecoration = "Bold"))

```

### Agonist Vs DMSO CTL08

#### All

```{r}
list_DEA_CTL08 <- vector("list", length(names(DEA_CTL04))) %>% setNames(names(DEA_CTL04)) #keep CTL04 to have the same order in the final file

for (Cond in names(list_DEA_CTL08)) {
  list_DEA_CTL08[[Cond]] <- DEA_CTL08[[Cond]]$Agonist$Res %>% as.data.frame()
}

list_DEA_CTL08 <- list_DEA_CTL08 %>% setNames(paste0("DEA_", names(list_DEA_CTL08), "_AgvsDMSO"))

openxlsx::write.xlsx(list_DEA_CTL08, paste0(params$OutputFolder, "DEA_CTL08_AgvsDMSO.xlsx"), rowNames = TRUE, headerStyle = openxlsx::createStyle(textDecoration = "Bold"))
```

#### DEGs

```{r}
list_DEGs_CTL08 <- vector("list", length(names(DEA_CTL04))) %>% setNames(names(DEA_CTL04)) #keep CTL04 to have the same order in the final file

for (Cond in names(list_DEGs_CTL08)) {
  list_DEGs_CTL08[[Cond]] <- DEA_CTL08[[Cond]]$Agonist$DEGs %>% arrange(padj)
}


list_DEGs_CTL08 <- list_DEGs_CTL08 %>% setNames(paste0("DEGs_", names(list_DEGs_CTL08), "_AgvsDMSO"))

openxlsx::write.xlsx(list_DEGs_CTL08, paste0(params$OutputFolder, "DEGs_CTL08_AgvsDMSO.xlsx"), rowNames = TRUE, headerStyle = openxlsx::createStyle(textDecoration = "Bold"))

```

### Inhibitor Vs DMSO CTL08

#### All

```{r}
list_DEA_CTL08 <- vector("list", length(names(DEA_CTL04))) %>% setNames(names(DEA_CTL04)) #keep CTL04 to have the same order in the final file

for (Cond in names(list_DEA_CTL08)[names(list_DEA_CTL08) != "Estr"]) { #skip Estr condition because Estr inhibitor not available for CTL08
  list_DEA_CTL08[[Cond]] <- DEA_CTL08[[Cond]]$Inhibitor$Res %>% as.data.frame()
}

list_DEA_CTL08 <- list_DEA_CTL08 %>% setNames(paste0("DEA_", names(list_DEA_CTL08), "_InhvsDMSO"))

openxlsx::write.xlsx(list_DEA_CTL08, paste0(params$OutputFolder, "DEA_CTL08_InhvsDMSO.xlsx"), rowNames = TRUE, headerStyle = openxlsx::createStyle(textDecoration = "Bold"))
```

#### DEGs

```{r}
list_DEGs_CTL08 <- vector("list", length(names(DEA_CTL04))) %>% setNames(names(DEA_CTL04)) #keep CTL04 to have the same order in the final file

for (Cond in names(list_DEGs_CTL08)[names(list_DEGs_CTL08) != "Estr"]) { #skip Estr condition because Estr inhibitor not available for CTL08
  list_DEGs_CTL08[[Cond]] <- DEA_CTL08[[Cond]]$Inhibitor$DEGs %>% arrange(padj)
}

list_DEGs_CTL08 <- list_DEGs_CTL08 %>% setNames(paste0("DEGs_", names(list_DEGs_CTL08), "_InhvsDMSO"))

openxlsx::write.xlsx(list_DEGs_CTL08, paste0(params$OutputFolder, "DEGs_CTL08_InhvsDMSO.xlsx"), rowNames = TRUE, headerStyle = openxlsx::createStyle(textDecoration = "Bold"))

```

```{r}
date()
sessionInfo()
```

